# Generated by Django 5.2.13 on 2026-05-16 07:28

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0005_alter_course_course_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Upload MP4 video for course preview (recommended 16:9 aspect ratio)",
                null=True,
                upload_to=course.models.course_video_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="video_url",
            field=models.URLField(
                blank=True, help_text="OR paste YouTube/Vimeo embed URL", null=True
            ),
        ),
    ]
