# Generated by Django 5.2.13 on 2026-06-15 21:18

import django.core.validators
import kyndryl.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KyndrylRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "mobile_number",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{10}$", "Enter a valid 10-digit mobile number"
                            )
                        ],
                    ),
                ),
                ("email_id", models.EmailField(max_length=254, unique=True)),
                (
                    "aadhar_number",
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{12}$", "Enter a valid 12-digit Aadhaar number"
                            )
                        ],
                    ),
                ),
                (
                    "highest_qualification",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("10th", "Class 10th"),
                            ("12th", "Class 12th"),
                            ("diploma", "Diploma"),
                            ("graduate", "Graduate"),
                            ("postgraduate", "Postgraduate"),
                            ("phd", "PhD"),
                            ("working_professional", "Working Professional"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("sc", "SC"),
                            ("st", "ST"),
                            ("ews", "EWS"),
                            ("obc", "OBC"),
                            ("pwd", "PWD"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "pin_code",
                    models.CharField(
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{6}$", "Enter a valid 6-digit pin code"
                            )
                        ],
                    ),
                ),
                (
                    "current_employment_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unemployed", "Unemployed"),
                            (
                                "employed_technical_upgradation_required",
                                "Employed & Technical Upgradation Required",
                            ),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "beneficiary_belonging",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ews", "Economically Weaker Section (EWS)"),
                            (
                                "tier2_tier3",
                                "Place of Residence in Tier 2 / Tier 3 City",
                            ),
                            ("minority_community", "Minority Community"),
                            ("women", "Women of any category"),
                            (
                                "middle_class",
                                "Jobseeker belonging to Middle Class Family",
                            ),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "expertise_in_cloud_computing",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("basic_level", "Basic Level"),
                            ("middle_level", "Middle Level"),
                            ("advance_level", "Advance Level"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "father_occupation",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "mother_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "mother_occupation",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="kyndryl_registration/photos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            ),
                            kyndryl.models.validate_file_size,
                        ],
                    ),
                ),
                (
                    "aadhaar_card",
                    models.FileField(
                        upload_to="kyndryl_registration/aadhaar/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                            ),
                            kyndryl.models.validate_file_size,
                        ],
                    ),
                ),
                (
                    "highest_qualification_certificate",
                    models.FileField(
                        upload_to="kyndryl_registration/certificates/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                            ),
                            kyndryl.models.validate_file_size,
                        ],
                    ),
                ),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-registration_date"],
                "indexes": [
                    models.Index(
                        fields=["email_id"], name="kyndryl_kyn_email_i_b74fb1_idx"
                    ),
                    models.Index(
                        fields=["mobile_number"], name="kyndryl_kyn_mobile__fa49b0_idx"
                    ),
                    models.Index(
                        fields=["registration_number"],
                        name="kyndryl_kyn_registr_fc8f40_idx",
                    ),
                ],
            },
        ),
    ]
