# Generated by Django 5.2.13 on 2026-06-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kyndryl", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kyndrylregistration",
            name="highest_qualification_certificate_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
