# Generated by Django 5.2.13 on 2026-06-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "kyndryl",
            "0003_alter_kyndrylregistration_highest_qualification_certificate_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="kyndrylregistration",
            name="highest_qualification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("10th", "Class 10th"),
                    ("12th", "Class 12th"),
                    ("diploma", "Diploma"),
                    ("3rd_year_graduation", "3rd Year in Graduation"),
                    ("4th_year_graduation", "4th Year in Graduation"),
                    ("graduate", "Graduate"),
                    ("postgraduate", "Postgraduate"),
                    ("phd", "PhD"),
                    ("working_professional", "Working Professional"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
