# Generated by Django 5.2.15 on 2026-07-02 05:38

import django.core.validators
import event.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Event title (required)", max_length=255
                    ),
                ),
                ("event_date", models.DateTimeField(blank=True, null=True)),
                ("registration_deadline", models.DateTimeField(blank=True, null=True)),
                ("subtitle", models.CharField(blank=True, max_length=500, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="events/images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg"]
                            ),
                            event.models.validate_image_size,
                        ],
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated skill chips, e.g. HTML, CSS, Python",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="Link shown as the CTA button", null=True
                    ),
                ),
                (
                    "show_qr",
                    models.BooleanField(
                        default=False,
                        help_text="Generate & show a QR code that points to the URL above",
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="events/qrcodes/",
                    ),
                ),
                (
                    "logo_count",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "One Logo"), (2, "Two Logos")],
                        default=1,
                        null=True,
                    ),
                ),
                (
                    "logo1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="events/logos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg"]
                            ),
                            event.models.validate_image_size,
                        ],
                    ),
                ),
                (
                    "logo2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="events/logos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg"]
                            ),
                            event.models.validate_image_size,
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "card_width",
                    models.CharField(
                        choices=[
                            ("full", "Full Screen Width"),
                            ("80", "80% of Screen Width"),
                        ],
                        default="80",
                        max_length=10,
                    ),
                ),
                (
                    "corner_style",
                    models.CharField(
                        choices=[("sharp", "Sharp"), ("round", "Round")],
                        default="round",
                        max_length=10,
                    ),
                ),
                (
                    "bg_type",
                    models.CharField(
                        choices=[("solid", "Solid Color"), ("gradient", "Gradient")],
                        default="gradient",
                        max_length=10,
                    ),
                ),
                (
                    "bg_color",
                    models.CharField(
                        default="#ffffff",
                        help_text="Used only when Background Type = Solid",
                        max_length=20,
                    ),
                ),
                ("gradient_start", models.CharField(default="#0f172a", max_length=20)),
                ("gradient_end", models.CharField(default="#1d4ed8", max_length=20)),
                ("accent_color", models.CharField(default="#eab308", max_length=20)),
                ("title_color", models.CharField(default="#0f172a", max_length=20)),
                ("subtitle_color", models.CharField(default="#1d4ed8", max_length=20)),
                ("text_color", models.CharField(default="#334155", max_length=20)),
                ("button_color", models.CharField(default="#1d4ed8", max_length=20)),
                (
                    "logo_position",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("center", "Center"),
                            ("right", "Right"),
                        ],
                        default="center",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
