# Generated by Django 5.2.15 on 2026-07-02 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image_size",
            field=models.PositiveIntegerField(
                default=360,
                help_text="Event image max-height in px (recommended 250-450)",
                validators=[
                    django.core.validators.MinValueValidator(120),
                    django.core.validators.MaxValueValidator(800),
                ],
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="logo_size",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Logo height in px (recommended 80-120)",
                validators=[
                    django.core.validators.MinValueValidator(40),
                    django.core.validators.MaxValueValidator(200),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="subtitle_color",
            field=models.CharField(default="#e2e8f0", max_length=20),
        ),
        migrations.AlterField(
            model_name="event",
            name="title_color",
            field=models.CharField(default="#ffffff", max_length=20),
        ),
    ]
