# Generated by Django 5.2.15 on 2026-07-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0002_event_image_size_event_logo_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="date_badge_color",
            field=models.CharField(default="#86efac", max_length=20),
        ),
        migrations.AddField(
            model_name="event",
            name="deadline_badge_color",
            field=models.CharField(default="#e9d5ff", max_length=20),
        ),
    ]
