# Generated by Django 5.2.15 on 2026-07-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0003_event_date_badge_color_event_deadline_badge_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventDisplaySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_mode",
                    models.CharField(
                        choices=[
                            ("stacked", "Stacked — one below another"),
                            ("carousel", "Carousel — auto-scrolling, one at a time"),
                            ("hidden", "Hidden — do not show on homepage"),
                        ],
                        default="stacked",
                        max_length=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Event Display Settings",
                "verbose_name_plural": "Event Display Settings",
            },
        ),
    ]
