# Generated by Django 5.2.13 on 2026-06-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0002_alter_student_preferred_centre"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="city",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("Other", "Other")],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="institute_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="state",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
