# Generated by Django 5.2.13 on 2026-06-14 08:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "registration",
            "0003_student_city_student_gender_student_institute_name_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Certificate",
        ),
    ]
