# Generated by Django 5.2.13 on 2026-05-19 15:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("registration", "0002_alter_student_preferred_centre"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateDesign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Certificate of Completion", max_length=200
                    ),
                ),
                ("subtitle", models.CharField(blank=True, max_length=200)),
                (
                    "body_text",
                    models.TextField(
                        default="This certificate is proudly presented to"
                    ),
                ),
                (
                    "completion_text",
                    models.CharField(
                        default="for successfully completing the course", max_length=200
                    ),
                ),
                (
                    "logo_position",
                    models.CharField(
                        choices=[
                            ("center", "Center"),
                            ("left", "Left"),
                            ("right", "Right"),
                            ("both", "Both Sides"),
                        ],
                        default="center",
                        max_length=20,
                    ),
                ),
                (
                    "institute_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="certificates/logos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg", "svg"]
                            )
                        ],
                    ),
                ),
                (
                    "secondary_logo",
                    models.ImageField(
                        blank=True,
                        help_text="Optional second logo (for left/right layout)",
                        null=True,
                        upload_to="certificates/logos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg", "svg"]
                            )
                        ],
                    ),
                ),
                ("signature_name_1", models.CharField(blank=True, max_length=200)),
                (
                    "signature_designation_1",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "signature_image_1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="certificates/signatures/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg", "svg"]
                            )
                        ],
                    ),
                ),
                (
                    "signature_name_2",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "signature_designation_2",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "signature_image_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="certificates/signatures/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg", "svg"]
                            )
                        ],
                    ),
                ),
                ("border_color", models.CharField(default="#1e3a8a", max_length=20)),
                ("primary_color", models.CharField(default="#1e3a8a", max_length=20)),
                ("secondary_color", models.CharField(default="#475569", max_length=20)),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="certificates/backgrounds/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg"]
                            )
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_active", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentCertificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                (
                    "issue_date",
                    models.DateField(help_text="Date when certificate is issued"),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="certificates/issued/"
                    ),
                ),
                (
                    "issued_by",
                    models.CharField(
                        blank=True,
                        help_text="Name of issuing authority",
                        max_length=100,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "design",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="certificate.certificatedesign",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_certificate",
                        to="registration.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date"],
            },
        ),
    ]
