# Generated by Django 5.2.13 on 2026-05-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificatedesign",
            name="signatory_count",
            field=models.IntegerField(
                choices=[(1, "One Signatory"), (2, "Two Signatories")],
                default=2,
                help_text="Number of signatories on certificate",
            ),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="signature_1_position",
            field=models.CharField(
                choices=[("left", "Left"), ("center", "Center"), ("right", "Right")],
                default="left",
                help_text="Position of first signature (applies when only one signatory)",
                max_length=20,
            ),
        ),
    ]
