# Generated by Django 5.2.13 on 2026-05-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificate", "0002_certificatedesign_signatory_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificatedesign",
            name="signatory_count",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2")],
                default=2,
                help_text="Number of signatories on certificate",
            ),
        ),
    ]
