# Generated by Django 5.2.13 on 2026-05-21 05:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificate", "0003_alter_certificatedesign_signatory_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="certificatedesign",
            old_name="signature_designation_1",
            new_name="signature_1_designation",
        ),
        migrations.RenameField(
            model_name="certificatedesign",
            old_name="signature_image_1",
            new_name="signature_1_image",
        ),
        migrations.RenameField(
            model_name="certificatedesign",
            old_name="signature_name_1",
            new_name="signature_1_name",
        ),
        migrations.RenameField(
            model_name="certificatedesign",
            old_name="signature_designation_2",
            new_name="signature_2_designation",
        ),
        migrations.RenameField(
            model_name="certificatedesign",
            old_name="signature_image_2",
            new_name="signature_2_image",
        ),
        migrations.RenameField(
            model_name="certificatedesign",
            old_name="signature_name_2",
            new_name="signature_2_name",
        ),
        migrations.RemoveField(
            model_name="certificatedesign",
            name="body_text",
        ),
        migrations.RemoveField(
            model_name="certificatedesign",
            name="completion_text",
        ),
        migrations.RemoveField(
            model_name="certificatedesign",
            name="primary_color",
        ),
        migrations.RemoveField(
            model_name="certificatedesign",
            name="secondary_color",
        ),
        migrations.RemoveField(
            model_name="certificatedesign",
            name="subtitle",
        ),
        migrations.RemoveField(
            model_name="certificatedesign",
            name="title",
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="body_font_size",
            field=models.IntegerField(default=14, help_text="Font size for body text"),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="body_text_color",
            field=models.CharField(
                default="#000000", help_text="Color for body text (hex)", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="body_text_template",
            field=models.TextField(
                default="This certificate is proudly presented to {student_name} for successfully completing the course {course_name} from {start_date} to {end_date}.",
                help_text="Use placeholders: {student_name}, {course_name}, {start_date}, {end_date}, {event_date}, {registration_number}, {institute_name}, {duration}",
            ),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="border_width",
            field=models.IntegerField(default=3, help_text="Border width in pixels"),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="certificate_title",
            field=models.CharField(default="CERTIFICATE OF COMPLETION", max_length=200),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="footer_font_size",
            field=models.IntegerField(default=9, help_text="Font size for footer text"),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="header_subtitle",
            field=models.CharField(
                blank=True,
                help_text="Brief intro / one liner about the institute",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="header_title",
            field=models.CharField(
                default="NIELIT Delhi",
                help_text="Institute name at the top",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="logo_size",
            field=models.IntegerField(default=80, help_text="Logo size in pixels"),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="show_certificate_number",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="show_issue_date",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="show_registration_number",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="show_student_id",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="title_color",
            field=models.CharField(
                default="#1e3a8a", help_text="Color for title (hex)", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="title_font_size",
            field=models.IntegerField(default=28, help_text="Font size for title"),
        ),
        migrations.AlterField(
            model_name="certificatedesign",
            name="logo_position",
            field=models.CharField(
                choices=[
                    ("center", "Center"),
                    ("left", "Left"),
                    ("right", "Right"),
                    ("both", "Both Sides"),
                    ("none", "No Logo"),
                ],
                default="center",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="certificatedesign",
            name="secondary_logo",
            field=models.ImageField(
                blank=True,
                help_text="Optional second logo (for both sides layout)",
                null=True,
                upload_to="certificates/logos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg", "svg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="certificatedesign",
            name="signatory_count",
            field=models.IntegerField(
                choices=[(1, "One Signatory"), (2, "Two Signatories")], default=2
            ),
        ),
        migrations.AlterField(
            model_name="certificatedesign",
            name="signature_1_position",
            field=models.CharField(
                choices=[("left", "Left"), ("center", "Center"), ("right", "Right")],
                default="left",
                max_length=20,
            ),
        ),
    ]
