# Generated by Django 5.2.13 on 2026-06-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "certificate",
            "0004_rename_signature_designation_1_certificatedesign_signature_1_designation_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="certificatedesign",
            name="line_1_text",
            field=models.CharField(
                default="This certificate is proudly presented to",
                help_text="Line 1 text (simple text)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="line_2_color",
            field=models.CharField(
                default="#1e3a8a", help_text="Color for line 2", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="line_2_custom_text",
            field=models.CharField(
                blank=True,
                help_text="Custom text instead of student name",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="line_2_font_size",
            field=models.IntegerField(default=32, help_text="Font size for line 2"),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="line_2_student_name",
            field=models.BooleanField(
                default=True, help_text="Show student name on line 2"
            ),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="line_3_text",
            field=models.CharField(
                default="for successfully completing the",
                help_text="Line 3 text (simple text)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="line_4_color",
            field=models.CharField(
                default="#1e3a8a", help_text="Color for line 4", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="line_4_custom_text",
            field=models.CharField(
                blank=True,
                help_text="Custom text instead of course name",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="line_4_font_size",
            field=models.IntegerField(default=20, help_text="Font size for line 4"),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="line_4_show_course",
            field=models.BooleanField(
                default=True, help_text="Show course/event name on line 4"
            ),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="line_5_color",
            field=models.CharField(
                default="#000000", help_text="Color for line 5", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="line_5_custom_text",
            field=models.CharField(
                blank=True, help_text="Custom text for date line", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="line_5_date_range",
            field=models.BooleanField(
                default=True, help_text="Show date range on line 5"
            ),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="line_5_font_size",
            field=models.IntegerField(default=14, help_text="Font size for line 5"),
        ),
    ]
