# Generated by Django 5.2.13 on 2026-06-05 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("certificate", "0005_certificatedesign_line_1_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificatedesign",
            name="body_font_size",
        ),
        migrations.RemoveField(
            model_name="certificatedesign",
            name="body_text_color",
        ),
        migrations.RemoveField(
            model_name="certificatedesign",
            name="body_text_template",
        ),
    ]
