# Generated by Django 5.2.13 on 2026-06-06 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("certificate", "0006_remove_certificatedesign_body_font_size_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentcertificate",
            name="pdf_file",
        ),
    ]
