# Generated by Django 5.2.13 on 2026-06-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificate", "0007_remove_studentcertificate_pdf_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificatedesign",
            name="qr_code_position",
            field=models.CharField(
                choices=[
                    ("bottom-left", "Bottom Left"),
                    ("bottom-right", "Bottom Right"),
                    ("bottom-center", "Bottom Center"),
                ],
                default="bottom-right",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="qr_code_size",
            field=models.IntegerField(default=80, help_text="QR code size in pixels"),
        ),
        migrations.AddField(
            model_name="certificatedesign",
            name="show_qr_code",
            field=models.BooleanField(
                default=True, help_text="Show QR code on certificate"
            ),
        ),
    ]
