# Generated by Django 5.2.15 on 2026-07-08 05:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="When ON the form is publicly accessible at its URL.",
                    ),
                ),
                (
                    "allow_multiple",
                    models.BooleanField(
                        default=True,
                        help_text="Allow the same visitor to submit more than once.",
                    ),
                ),
                (
                    "success_message",
                    models.TextField(
                        default="Thank you! Your response has been recorded."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FormField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "field_name",
                    models.SlugField(
                        blank=True,
                        help_text="Machine name used as the column key. Auto-generated from the label.",
                        max_length=100,
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Short text"),
                            ("textarea", "Paragraph"),
                            ("number", "Number"),
                            ("email", "Email"),
                            ("tel", "Contact number"),
                            ("url", "URL"),
                            ("select", "Dropdown (single)"),
                            ("radio", "Multiple choice (single)"),
                            ("checkbox", "Checkboxes (multiple)"),
                            ("date", "Date"),
                            ("datetime", "Date & time"),
                            ("file", "File upload"),
                            ("image", "Image upload"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("placeholder", models.CharField(blank=True, max_length=255)),
                ("help_text", models.CharField(blank=True, max_length=255)),
                ("required", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "options",
                    models.TextField(
                        blank=True,
                        help_text="One option per line (for dropdown / choice fields).",
                    ),
                ),
                ("min_length", models.PositiveIntegerField(blank=True, null=True)),
                ("max_length", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "validation_type",
                    models.CharField(
                        choices=[
                            ("none", "No restriction"),
                            ("numeric", "Numbers only"),
                            ("alpha", "Letters only"),
                            ("alphanumeric", "Letters & numbers only"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="form_builder2.form",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="FormResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="form_builder2.form",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="FormResponseFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="form_uploads/%Y/%m/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="form_builder2.formfield",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="form_builder2.formresponse",
                    ),
                ),
            ],
        ),
    ]
