# Generated by Django 5.2.15 on 2026-07-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form_builder2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="is_pinned",
            field=models.BooleanField(
                default=False,
                help_text="Pin this form to the sidebar for quick access.",
            ),
        ),
    ]
