# Generated by Django 5.2.13 on 2026-05-14 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
            },
        ),
        migrations.AlterModelOptions(
            name="carouselimage",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "Carousel Image",
                "verbose_name_plural": "Carousel Images",
            },
        ),
        migrations.RenameField(
            model_name="announcement",
            old_name="display_order",
            new_name="order",
        ),
        migrations.RenameField(
            model_name="carouselimage",
            old_name="display_order",
            new_name="order",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="carouselimage",
            name="alt_text",
        ),
        migrations.RemoveField(
            model_name="carouselimage",
            name="description",
        ),
        migrations.RemoveField(
            model_name="carouselimage",
            name="link_url",
        ),
        migrations.RemoveField(
            model_name="carouselimage",
            name="title",
        ),
        migrations.RemoveField(
            model_name="carouselimage",
            name="updated_at",
        ),
    ]
